/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypackage;

import javax.swing.*;
import java.awt.*;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author ahnaf
 */
public class Greeting extends javax.swing.JFrame {

    /**
     * Creates new form Greeting
     */
    public Greeting() {
        initComponents();
        updateProgressBar();
        startAnimation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SWGothe", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eid Mubarak");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 170, 30));

        jButton1.setBackground(new java.awt.Color(50, 149, 50));
        jButton1.setText("Credit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 303, 70, 20));

        progressBar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        progressBar.setName(""); // NOI18N
        progressBar.setStringPainted(true);
        getContentPane().add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("On this joyous occasion, I’m honored to present my entry for the");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Eid challenge. May this Eid bring peace, happiness, and countless");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("blessings to you and your loved ones. Thank you for inspiring us to be ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("creative and strive for excellence. Wishing you a prosperous and joyful ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Eid filled with love and smile! 🌸🎉");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/inline_image_preview.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Timer animationTimer;
    private int r = 0, g = 255, b = 0; // Start with green
    private int step = 5; // Color change per step

    private void startAnimation() {
        animationTimer = new Timer(100, e -> {
            if (g == 255 && r < 255 && b == 0) {
                r += step;  // Green → Yellow
            } else if (r == 255 && g > 0 && b == 0) {
                g -= step;  // Yellow → Red
            } else if (r == 255 && b < 255 && g == 0) {
                b += step;  // Red → Magenta
            } else if (b == 255 && r > 0 && g == 0) {
                r -= step;  // Magenta → Blue
            } else if (b == 255 && g < 255 && r == 0) {
                g += step;  // Blue → Cyan
            } else if (g == 255 && b > 0 && r == 0) {
                b -= step;  // Cyan → Green
            }

            jLabel1.setForeground(new Color(r, g, b)); // Apply new color
        });
        animationTimer.start();
    }

    private void updateProgressBar() {
        // Define Ramadan start and Eid date
        LocalDate startOfRamadan = LocalDate.of(2025, 3, 1);  // 1 March 2025
        LocalDate eidDate = LocalDate.of(2025, 4, 1);  // 1 April 2025

        // today's date 
        LocalDate today = LocalDate.now();

        // Calculate total days from Ramadan start to Eid from 1 Mar to 1 Apr in 2025
        long totalDays = ChronoUnit.DAYS.between(startOfRamadan, eidDate);


        // Calculate how many days have passed since Ramadan started
        long daysPassed = ChronoUnit.DAYS.between(startOfRamadan, today);

        // Clamp daysPassed between 0 and totalDays
        if (daysPassed < 0) {
            // days rest hobe
            daysPassed = 0;
        } else if (daysPassed > totalDays) {
            // Eid day shai:)
            daysPassed = totalDays;
        }

        long daysLeft = totalDays - daysPassed;

        // progress bar value
        progressBar.setMinimum(0);
        progressBar.setMaximum((int) totalDays);
        progressBar.setValue((int) daysPassed);

        // Display "X days left for Eid!"
        progressBar.setString(daysLeft + " days left for Eid!");
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //System.out.println("Thnaks Sir");
        JOptionPane.showMessageDialog(this, "Created by: Ahnaf\nSubmited to: DSU sir ");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Greeting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Greeting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Greeting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Greeting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Greeting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
